services:
  fastchannelsv2:
    image: fastchannelsv2:latest
    container_name: fastchannelsv2
    restart: unless-stopped
    pull_policy: never
    ports:
      - "5523:5523"
    volumes:
      - db_data:/data

volumes:
  db_data:
