version: '3.9'

services:
  fastchannelsv2:
    image: ghcr.io/${GHCR_OWNER:-kineticman}/fastchannelsv2:${FASTCHANNELSV2_IMAGE_TAG:-latest}
    container_name: fastchannelsv2
    restart: unless-stopped
    ports:
      - "5523:5523"
    volumes:
      - db_data:/data

volumes:
  db_data:
