version: '3.9'

services:
  playlistmanager:
    image: ghcr.io/${GHCR_OWNER:-kineticman}/playlistmanager:${PLAYLISTMANAGER_IMAGE_TAG:-latest}
    container_name: playlistmanager
    restart: unless-stopped
    ports:
      - "5523:5523"
    volumes:
      - db_data:/data

volumes:
  db_data:
